spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  profiles:
    active: local
    include: secret

  jpa:
    hibernate:
      ddl-auto: create