spring:

  datasource:
#    url: jdbc:mysql://ec2-18-233-162-22.compute-1.amazonaws.com/ChattingMachineDB
#    username: SunnyHeo
#    password: mypassword
#    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver


  profiles:
    active: local
    include: secret

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  messages:
    basename: messageSource/exception, messageSource/validation

  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
    hibernate:
      ddl-auto: create

logging.level.org.springframework.web: DEBUG
logging.level.org.hibernate: ERROR