spring:

  datasource:
    url: jdbc:mysql://ec2-3-82-102-70.compute-1.amazonaws.com/ChattingMachineDB
    username: SunnyHeo
    password: mypassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:h2:mem:test
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver


  profiles:
    active: local
    include: secret

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  messages:
    basename: messageSource/exception, messageSource/validation

  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
    hibernate:
      ddl-auto: create
    open-in-view: off
    show-sql: true

logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR

server:
  port: 8088